[project]
name = "wt"
version = "0.1.0"
description = "Simple tool to work with git worktrees"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "iterfzf>=1.7.0.62.0",
]

[tool.basedpyright]
allowedUntypedLibraries = ["iterfzf"]
typeCheckingMode = "standard"
